import { daysAgo } from '../ui';
import { Asset, AssetReview, HistoryEntry } from './types';
import { richContent } from './richContent';
import { makeMoreAssets } from './moreAssets';

const base = (over: Partial<Asset> & Pick<Asset, 'id' | 'type' | 'displayName'>): Asset => ({
  familyId: over.id,
  isFamilyHead: true,
  releaseNotes: '',
  changeType: null,
  name: over.displayName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  shortDescription: '',
  description: '',
  category: 'IT & Engineering',
  subCategory: '',
  tags: [],
  status: 'PUBLISHED',
  semanticVersion: '1.0.0',
  accessibility: 'PRIVATE',
  marketplaceLive: false,
  owner: 'Workspace Admin',
  createdAt: daysAgo(40),
  updatedAt: daysAgo(3),
  capabilityIds: [],
  stats: { views: 0, installs: 0, favorites: 0, rating: 0, reviewCount: 0 },
  ...over,
});

/* ── Folders (capabilities) ─────────────────────────────────────────────── */

const folders: Asset[] = [
  base({
    id: 'CAP-0001',
    type: 'capability',
    displayName: 'Requirements Engineering',
    shortDescription: 'Everything needed to turn raw business input into signed-off requirements.',
    description: 'Skills, knowledge and guardrails used across BRD, FRD and SRS generation for solution planning.',
    category: 'IT & Engineering',
    subCategory: 'Business Analysis',
    department: 'Product',
    tags: ['requirements', 'brd', 'frd'],
    linkedSkillIds: ['SKL-0001', 'SKL-0002', 'SKL-0007'],
    updatedAt: daysAgo(2),
  }),
  base({
    id: 'CAP-0002',
    type: 'capability',
    displayName: 'Customer Support Automation',
    shortDescription: 'Triage, summarise and respond to customer conversations.',
    description: 'Used by the support desk assistants for email and chat triage.',
    category: 'Customer Support',
    subCategory: 'Ticketing',
    department: 'Support',
    tags: ['support', 'triage'],
    linkedSkillIds: ['SKL-0003', 'SKL-0008'],
    updatedAt: daysAgo(6),
  }),
  base({
    id: 'CAP-0003',
    type: 'capability',
    displayName: 'Architecture & Review',
    shortDescription: 'Code, API and architecture review helpers for engineering teams.',
    description: 'Review assistants that apply the organisation architecture standards.',
    category: 'IT & Engineering',
    subCategory: 'Architecture',
    department: 'Engineering',
    tags: ['architecture', 'review', 'api'],
    linkedSkillIds: ['SKL-0004', 'SKL-0005'],
    updatedAt: daysAgo(9),
  }),
  base({
    id: 'CAP-0004',
    type: 'capability',
    displayName: 'Finance Reporting',
    shortDescription: 'Month-end narratives and variance explanations.',
    description: 'Analyst helpers for finance reporting.',
    category: 'Finance & Accounting',
    subCategory: 'Reporting',
    department: 'Finance',
    tags: ['finance', 'reporting'],
    linkedSkillIds: ['SKL-0006'],
    updatedAt: daysAgo(14),
  }),
];

/* ── Skills ─────────────────────────────────────────────────────────────── */

const skills: Asset[] = [
  base({
    id: 'SKL-0001',
    type: 'skill',
    displayName: 'Generate FRD Document',
    shortDescription: 'Turns an approved BRD into a structured Functional Requirements Document.',
    description: 'Reads the approved business requirements and produces functional requirements with traceability IDs, actors, acceptance criteria and open questions.',
    category: 'IT & Engineering',
    subCategory: 'Document Generation',
    department: 'Product',
    tags: ['frd', 'documentation', 'requirements'],
    skillType: 'GENERATION',
    status: 'PUBLISHED',
    semanticVersion: '1.1.0',
    familyId: 'FAM-FRD',
    releaseNotes: 'Added acceptance-criteria section and traceability matrix.',
    changeType: 'MINOR',
    accessibility: 'PUBLIC',
    marketplaceLive: true,
    capabilityIds: ['CAP-0001'],
    knowledgeIds: ['KNW-0001', 'KNW-0002'],
    instructionIds: ['INS-0001', 'INS-0002'],
    policyIds: ['POL-0001'],
    promptTemplate:
      'Act as a senior Business Analyst. Given the approved BRD below, produce a Functional Requirements Document.\n\nRules:\n1. Number every requirement FR-001, FR-002 …\n2. Each requirement lists actor, trigger, behaviour and acceptance criteria.\n3. Flag any ambiguity under "Open Questions" — never invent facts.\n4. Keep the language testable and unambiguous.\n\n{{brd_content}}',
    examples: [
      { title: 'Standard BRD input', input: 'BRD: Customers must be able to reset their password by email.', output: 'FR-001 Password reset request — Actor: Customer — Trigger: "Forgot password" …' },
    ],
    stats: { views: 1280, installs: 214, favorites: 96, rating: 4.7, reviewCount: 38 },
    createdAt: daysAgo(70),
    updatedAt: daysAgo(2),
  }),
  base({
    id: 'SKL-0001-D',
    type: 'skill',
    displayName: 'Generate FRD Document',
    familyId: 'FAM-FRD',
    isFamilyHead: false,
    shortDescription: 'Turns an approved BRD into a structured Functional Requirements Document.',
    skillType: 'GENERATION',
    status: 'DRAFT',
    semanticVersion: '1.2.0',
    releaseNotes: 'WIP: support multilingual BRDs.',
    changeType: 'MINOR',
    capabilityIds: ['CAP-0001'],
    knowledgeIds: ['KNW-0001'],
    instructionIds: ['INS-0001'],
    policyIds: ['POL-0001'],
    promptTemplate: 'Act as a senior Business Analyst. (draft revision) …',
    tags: ['frd', 'documentation'],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  }),
  base({
    id: 'SKL-0001-V0',
    type: 'skill',
    displayName: 'Generate FRD Document',
    familyId: 'FAM-FRD',
    isFamilyHead: false,
    shortDescription: 'Turns an approved BRD into a structured Functional Requirements Document.',
    skillType: 'GENERATION',
    status: 'PUBLISHED',
    semanticVersion: '1.0.0',
    releaseNotes: 'Initial release.',
    changeType: 'MAJOR',
    marketplaceLive: false,
    capabilityIds: ['CAP-0001'],
    tags: ['frd'],
    promptTemplate: 'Act as a Business Analyst …',
    createdAt: daysAgo(70),
    updatedAt: daysAgo(40),
  }),
  base({
    id: 'SKL-0002',
    type: 'skill',
    displayName: 'Business Requirements Summarizer',
    shortDescription: 'Condenses long stakeholder interviews into a one-page business requirements summary.',
    description: 'Extracts goals, pain points, constraints and success metrics from interview transcripts.',
    category: 'IT & Engineering',
    subCategory: 'Analysis',
    department: 'Product',
    tags: ['summary', 'brd'],
    skillType: 'ANALYSIS',
    status: 'PUBLISHED',
    semanticVersion: '1.0.2',
    accessibility: 'TEAM',
    capabilityIds: ['CAP-0001'],
    knowledgeIds: ['KNW-0001'],
    instructionIds: ['INS-0002'],
    policyIds: ['POL-0002'],
    promptTemplate: 'Summarise the following stakeholder transcript into: Goals, Pain Points, Constraints, Success Metrics.\n\n{{transcript}}',
    examples: [],
    stats: { views: 420, installs: 0, favorites: 31, rating: 4.4, reviewCount: 9 },
    updatedAt: daysAgo(5),
  }),
  base({
    id: 'SKL-0003',
    type: 'skill',
    displayName: 'Customer Email Triage',
    shortDescription: 'Classifies inbound support email by intent, urgency and sentiment.',
    description: 'Routes email to the right queue and drafts a first-response suggestion.',
    category: 'Customer Support',
    subCategory: 'Ticketing',
    department: 'Support',
    tags: ['support', 'email', 'classification'],
    skillType: 'CLASSIFICATION',
    status: 'PUBLISHED',
    semanticVersion: '2.0.0',
    accessibility: 'PUBLIC',
    marketplaceLive: true,
    capabilityIds: ['CAP-0002'],
    knowledgeIds: ['KNW-0003'],
    instructionIds: ['INS-0003'],
    policyIds: ['POL-0002', 'POL-0003'],
    promptTemplate: 'Classify the email below. Return JSON {intent, urgency, sentiment, queue, suggestedReply}.\n\n{{email}}',
    examples: [{ title: 'Billing complaint', input: 'I was charged twice this month!!', output: '{"intent":"billing","urgency":"high","sentiment":"negative","queue":"billing"}' }],
    stats: { views: 2240, installs: 502, favorites: 211, rating: 4.8, reviewCount: 74 },
    updatedAt: daysAgo(1),
  }),
  base({
    id: 'SKL-0004',
    type: 'skill',
    displayName: 'API Contract Reviewer',
    shortDescription: 'Reviews OpenAPI specs against the organisation API design guide.',
    description: 'Flags naming, versioning, pagination and error-model deviations and proposes fixes.',
    category: 'IT & Engineering',
    subCategory: 'API Design',
    department: 'Engineering',
    tags: ['api', 'openapi', 'review'],
    skillType: 'REVIEW',
    status: 'PUBLISHED',
    semanticVersion: '1.3.0',
    accessibility: 'TEAM',
    capabilityIds: ['CAP-0003'],
    knowledgeIds: ['KNW-0004'],
    instructionIds: ['INS-0004'],
    policyIds: ['POL-0004'],
    promptTemplate: 'You are an API governance reviewer. Compare the OpenAPI document with the API design guide and list findings by severity.\n\n{{openapi}}',
    stats: { views: 610, installs: 0, favorites: 44, rating: 4.5, reviewCount: 12 },
    updatedAt: daysAgo(8),
  }),
  base({
    id: 'SKL-0005',
    type: 'skill',
    displayName: 'Architecture Decision Drafter',
    shortDescription: 'Drafts an Architecture Decision Record from a problem statement and options.',
    description: 'Produces ADRs following the repository template, including consequences and trade-offs.',
    category: 'IT & Engineering',
    subCategory: 'Architecture',
    department: 'Engineering',
    tags: ['adr', 'architecture'],
    skillType: 'GENERATION',
    status: 'DRAFT',
    semanticVersion: '0.3.0',
    capabilityIds: ['CAP-0003'],
    knowledgeIds: ['KNW-0004'],
    instructionIds: ['INS-0004'],
    policyIds: [],
    promptTemplate: 'Draft an ADR using the template. Problem: {{problem}} Options: {{options}}',
    updatedAt: daysAgo(2),
  }),
  base({
    id: 'SKL-0006',
    type: 'skill',
    displayName: 'Monthly Variance Narrative',
    shortDescription: 'Explains budget-vs-actual variances in plain business language.',
    description: 'Takes a variance table and writes the commentary finance leaders expect.',
    category: 'Finance & Accounting',
    subCategory: 'Reporting',
    department: 'Finance',
    tags: ['finance', 'variance'],
    skillType: 'ANALYSIS',
    status: 'DEPRECATED',
    semanticVersion: '1.4.1',
    deprecationReason: 'Superseded by the new reporting narrative pack with currency normalisation.',
    capabilityIds: ['CAP-0004'],
    knowledgeIds: [],
    instructionIds: ['INS-0002'],
    policyIds: ['POL-0002'],
    promptTemplate: 'Write a variance narrative for the table below …\n\n{{table}}',
    stats: { views: 190, installs: 0, favorites: 6, rating: 4.0, reviewCount: 3 },
    updatedAt: daysAgo(20),
  }),
  base({
    id: 'SKL-0007',
    type: 'skill',
    displayName: 'User Story Splitter',
    shortDescription: 'Breaks epics into INVEST-compliant user stories with acceptance criteria.',
    description: 'Takes an epic and splits it into independent, estimable stories.',
    category: 'IT & Engineering',
    subCategory: 'Agile',
    department: 'Product',
    tags: ['agile', 'stories'],
    skillType: 'TASK',
    status: 'PUBLISHED',
    semanticVersion: '1.0.0',
    accessibility: 'PRIVATE',
    capabilityIds: ['CAP-0001'],
    knowledgeIds: ['KNW-0002'],
    instructionIds: ['INS-0001'],
    policyIds: [],
    promptTemplate: 'Split the epic into user stories …\n\n{{epic}}',
    stats: { views: 88, installs: 0, favorites: 5, rating: 0, reviewCount: 0 },
    updatedAt: daysAgo(11),
  }),
  base({
    id: 'SKL-0008',
    type: 'skill',
    displayName: 'Support Reply Composer',
    shortDescription: 'Installed from the marketplace — drafts tone-matched support replies.',
    description: 'Marketplace skill installed into this workspace and linked to its publisher.',
    category: 'Customer Support',
    subCategory: 'Response',
    department: 'Support',
    tags: ['support', 'reply'],
    skillType: 'GENERATION',
    status: 'PUBLISHED',
    semanticVersion: '3.1.0',
    acquisitionType: 'INSTALL',
    sourceAssetId: 'MKT-9912',
    owner: 'Helio Labs',
    capabilityIds: ['CAP-0002'],
    knowledgeIds: [],
    instructionIds: ['INS-0003'],
    policyIds: ['POL-0003'],
    promptTemplate: 'Compose a reply in the customer’s tone …',
    stats: { views: 5200, installs: 1840, favorites: 702, rating: 4.9, reviewCount: 201 },
    updatedAt: daysAgo(15),
  }),
  base({
    id: 'SKL-0009',
    type: 'skill',
    displayName: 'Meeting Action Extractor',
    shortDescription: 'Pulls owners, deadlines and decisions out of meeting transcripts.',
    description: '',
    category: 'General Utilities',
    tags: ['meetings'],
    skillType: 'TASK',
    status: 'DRAFT',
    semanticVersion: '0.1.0',
    capabilityIds: [],
    knowledgeIds: [],
    instructionIds: [],
    policyIds: [],
    promptTemplate: 'Extract actions from the transcript …',
    updatedAt: daysAgo(0),
  }),
];

/* ── Knowledge / Instructions / Policies ────────────────────────────────── */

const knowledge: Asset[] = [
  base({
    id: 'KNW-0001',
    type: 'knowledge',
    displayName: 'Business Analysis Standards',
    shortDescription: 'Organisation standards for writing BRDs, FRDs and SRS documents.',
    subType: 'ORGANIZATION',
    category: 'IT & Engineering',
    subCategory: 'Business Analysis',
    tags: ['standards', 'brd'],
    capabilityIds: ['CAP-0001'],
    content:
      '# Business Analysis Standards\n\n## BRD\n- State the business objective in one sentence.\n- List stakeholders with roles.\n- Every requirement needs a measurable success criterion.\n\n## FRD\n- Use FR-### identifiers.\n- Include actor, trigger, behaviour, acceptance criteria.\n\n## SRS\n- Separate functional and non-functional requirements.\n- Reference the FRD IDs for traceability.',
    updatedAt: daysAgo(7),
  }),
  base({
    id: 'KNW-0002',
    type: 'knowledge',
    displayName: 'Agile Estimation Guide',
    shortDescription: 'Story sizing, INVEST checklist and definition of ready.',
    subType: 'BEST_PRACTICE',
    category: 'IT & Engineering',
    tags: ['agile'],
    capabilityIds: ['CAP-0001'],
    content: '# Agile Estimation Guide\n\nUse relative sizing (1, 2, 3, 5, 8). A story is ready when it is Independent, Negotiable, Valuable, Estimable, Small and Testable.',
    updatedAt: daysAgo(12),
  }),
  base({
    id: 'KNW-0003',
    type: 'knowledge',
    displayName: 'Support Queue Taxonomy',
    shortDescription: 'Intent labels, queues and escalation paths for the support desk.',
    subType: 'PROCESS',
    category: 'Customer Support',
    tags: ['support', 'taxonomy'],
    capabilityIds: ['CAP-0002'],
    content: '# Queue Taxonomy\n\n| Intent | Queue | SLA |\n|---|---|---|\n| billing | Billing | 4h |\n| bug | Tier-2 | 8h |\n| how-to | Tier-1 | 24h |',
    updatedAt: daysAgo(16),
  }),
  base({
    id: 'KNW-0004',
    type: 'knowledge',
    displayName: 'API Design Guide v3',
    shortDescription: 'Naming, versioning, pagination and error model rules for all public APIs.',
    subType: 'TECHNICAL',
    category: 'IT & Engineering',
    subCategory: 'API Design',
    tags: ['api', 'guide'],
    capabilityIds: ['CAP-0003'],
    accessibility: 'TEAM',
    content: '# API Design Guide\n\n- Resource names are plural nouns.\n- Version in the URL: `/v1/`.\n- Pagination uses `cursor` + `limit`.\n- Errors follow RFC 7807 problem+json.',
    updatedAt: daysAgo(10),
  }),
  base({
    id: 'KNW-0005',
    type: 'knowledge',
    displayName: 'Glossary — Banking Terms',
    shortDescription: 'Domain glossary used for fintech solutions.',
    subType: 'DOMAIN',
    status: 'DRAFT',
    category: 'Finance & Accounting',
    tags: ['glossary'],
    capabilityIds: [],
    content: '# Glossary\n\n**KYC** — Know Your Customer …',
    updatedAt: daysAgo(3),
  }),
];

const instructions: Asset[] = [
  base({
    id: 'INS-0001',
    type: 'instruction',
    displayName: 'Requirement Writing Style',
    shortDescription: 'Tone, structure and wording rules for requirement statements.',
    subType: 'FORMATTING',
    category: 'IT & Engineering',
    tags: ['style'],
    capabilityIds: ['CAP-0001'],
    content: 'Always write requirements as "The system shall …". Use present tense. One requirement per sentence. Avoid "etc." and "and/or".',
    updatedAt: daysAgo(9),
  }),
  base({
    id: 'INS-0002',
    type: 'instruction',
    displayName: 'Respond in Structured Markdown',
    shortDescription: 'Use headings, tables and bullet lists for every long answer.',
    subType: 'FORMATTING',
    category: 'General Utilities',
    tags: ['markdown'],
    capabilityIds: ['CAP-0001', 'CAP-0004'],
    content: 'Respond in Markdown. Use H2 for sections, tables for comparisons, bullet lists for steps. Keep paragraphs under four lines.',
    updatedAt: daysAgo(18),
  }),
  base({
    id: 'INS-0003',
    type: 'instruction',
    displayName: 'Empathetic Support Tone',
    shortDescription: 'Warm, concise, accountable tone for customer-facing replies.',
    subType: 'ROLE',
    category: 'Customer Support',
    tags: ['tone'],
    capabilityIds: ['CAP-0002'],
    content: 'Acknowledge the customer’s feeling first. Own the problem. Offer the next step and a timeframe. Never blame the customer.',
    updatedAt: daysAgo(4),
  }),
  base({
    id: 'INS-0004',
    type: 'instruction',
    displayName: 'Code Review Checklist',
    shortDescription: 'Ordered checklist for reviewing changes: correctness, security, tests, style.',
    subType: 'QUALITY',
    category: 'IT & Engineering',
    tags: ['review'],
    capabilityIds: ['CAP-0003'],
    content: '1. Does it do what the ticket says?\n2. Are inputs validated?\n3. Any secrets or PII logged?\n4. Are there tests?\n5. Naming and style.',
    updatedAt: daysAgo(13),
  }),
];

const policies: Asset[] = [
  base({
    id: 'POL-0001',
    type: 'policy',
    displayName: 'No Invented Requirements',
    shortDescription: 'The AI must never fabricate facts that are not in the source documents.',
    subType: 'QUALITY',
    enforcementMode: 'MANDATORY',
    category: 'IT & Engineering',
    tags: ['quality', 'hallucination'],
    capabilityIds: ['CAP-0001'],
    content: 'If information is missing, list it under "Open Questions". Do not guess stakeholders, numbers, dates or systems.',
    updatedAt: daysAgo(6),
  }),
  base({
    id: 'POL-0002',
    type: 'policy',
    displayName: 'PII Redaction',
    shortDescription: 'Redact personal data before it is stored, logged or shared.',
    subType: 'PRIVACY',
    enforcementMode: 'MANDATORY',
    category: 'General Utilities',
    tags: ['privacy', 'gdpr'],
    capabilityIds: ['CAP-0002', 'CAP-0004'],
    content: 'Mask email addresses, phone numbers, national IDs and card numbers as [REDACTED]. Never echo them back in a response.',
    updatedAt: daysAgo(22),
  }),
  base({
    id: 'POL-0003',
    type: 'policy',
    displayName: 'No Legal or Refund Promises',
    shortDescription: 'Agents must not commit the company to refunds or legal positions.',
    subType: 'LEGAL',
    enforcementMode: 'RECOMMENDED',
    category: 'Customer Support',
    tags: ['legal'],
    capabilityIds: ['CAP-0002'],
    content: 'Do not promise refunds, credits or legal outcomes. Escalate those requests to a human agent.',
    updatedAt: daysAgo(17),
  }),
  base({
    id: 'POL-0004',
    type: 'policy',
    displayName: 'Secrets Must Never Be Echoed',
    shortDescription: 'API keys, tokens and passwords found in input must be masked.',
    subType: 'SECURITY',
    enforcementMode: 'MANDATORY',
    category: 'IT & Engineering',
    tags: ['security'],
    capabilityIds: ['CAP-0003'],
    content: 'If a string looks like a credential (AKIA…, sk-…, ghp_…), replace it with [SECRET] in the output.',
    updatedAt: daysAgo(30),
  }),
];

const withRich = (a: Asset): Asset => {
  const r = richContent[a.id];
  if (!r) return a;
  return { ...a, ...(r.description && { description: r.description }), ...(r.prompt && { promptTemplate: r.prompt }), ...(r.content && { content: r.content }) };
};

export const seedAssets: Asset[] = [...folders, ...skills, ...knowledge, ...instructions, ...policies, ...makeMoreAssets(base)].map(withRich);

export const seedReviews: AssetReview[] = [
  { id: 'R1', assetId: 'SKL-0001', author: 'Priya Menon', rating: 5, title: 'Saves hours every sprint', review: 'The traceability IDs line up perfectly with our QA tooling. We only had to edit a few acceptance criteria.', verified: true, helpful: 12, createdAt: daysAgo(9) },
  { id: 'R2', assetId: 'SKL-0001', author: 'Daniel Okafor', rating: 4, title: 'Great, needs multilingual support', review: 'Very solid output. Wish it handled Spanish BRDs — I see a draft version is on the way.', verified: true, helpful: 5, createdAt: daysAgo(21) },
  { id: 'R3', assetId: 'SKL-0001', author: 'Mei Lin', rating: 5, title: 'Best in class', review: 'Open Questions section is a game changer for review meetings.', verified: false, helpful: 3, createdAt: daysAgo(30) },
  { id: 'R4', assetId: 'SKL-0003', author: 'Carlos Vega', rating: 5, title: 'Routing accuracy is excellent', review: 'We cut manual triage by about 60% in the first month.', verified: true, helpful: 18, createdAt: daysAgo(5) },
  { id: 'R5', assetId: 'SKL-0003', author: 'Aisha Rahman', rating: 4, title: 'Good, tweak the taxonomy', review: 'Edit the knowledge asset to match your own queues for best results.', verified: true, helpful: 7, createdAt: daysAgo(12) },
  { id: 'R6', assetId: 'SKL-0004', author: 'Tom Becker', rating: 5, title: 'Catches versioning mistakes', review: 'Found three contract issues the humans missed.', verified: true, helpful: 4, createdAt: daysAgo(14) },
];

export const seedHistory: HistoryEntry[] = [
  { id: 'H1', familyId: 'FAM-FRD', assetId: 'SKL-0001-V0', action: 'CREATED', changedBy: 'Workspace Admin', changedAt: daysAgo(70), changes: [] },
  { id: 'H2', familyId: 'FAM-FRD', assetId: 'SKL-0001-V0', action: 'PUBLISHED', changedBy: 'Workspace Admin', changedAt: daysAgo(68), reason: 'Initial marketplace release', changes: [{ field: 'accessibility', from: 'PRIVATE', to: 'PUBLIC' }] },
  { id: 'H3', familyId: 'FAM-FRD', assetId: 'SKL-0001', action: 'VERSION_CREATED', changedBy: 'Workspace Admin', changedAt: daysAgo(45), reason: 'Add acceptance criteria', changes: [{ field: 'semanticVersion', from: '1.0.0', to: '1.1.0' }] },
  { id: 'H4', familyId: 'FAM-FRD', assetId: 'SKL-0001', action: 'UPDATED', changedBy: 'Workspace Admin', changedAt: daysAgo(44), changes: [{ field: 'promptTemplate', from: 'Act as a Business Analyst …', to: 'Act as a senior Business Analyst …' }, { field: 'tags', from: 'frd', to: 'frd, documentation, requirements' }] },
  { id: 'H5', familyId: 'FAM-FRD', assetId: 'SKL-0001', action: 'PUBLISHED', changedBy: 'Workspace Admin', changedAt: daysAgo(40), changes: [{ field: 'status', from: 'DRAFT', to: 'PUBLISHED' }] },
  { id: 'H6', familyId: 'FAM-FRD', assetId: 'SKL-0001-D', action: 'VERSION_CREATED', changedBy: 'Workspace Admin', changedAt: daysAgo(4), reason: 'Multilingual BRD support', changes: [{ field: 'semanticVersion', from: '1.1.0', to: '1.2.0' }] },
  { id: 'H7', familyId: 'SKL-0006', assetId: 'SKL-0006', action: 'DEPRECATED', changedBy: 'Workspace Admin', changedAt: daysAgo(20), reason: 'Superseded by the new reporting narrative pack.', changes: [{ field: 'status', from: 'PUBLISHED', to: 'DEPRECATED' }] },
];
